let games = [
  '3D Ultra Pinball',
  '3D Ultra Minigolf',
  'Action Soccer',
  'Actua Soccer',
  'Aladdin',
  'Anno 1602',
  'Arcade America',
  'Battle Chess',
  'Bernie',
  'Charlie the Clown',
  'Comix Zone',
  'Commander Keen in Goodbye Galaxy',
  'Commander Keen in Keen Dreams',
  'Conflict: Desert Storm',
  'Crazy Gravity',
  'Critical Mass',
  'Day of the Tentacle',
  'Death Rally',
  'Eight Ball Deluxe',
  'Epic Pinball',
  'Fire Fight',
  'Galactix',
  'GateWorld',
  'Glider 4.0',
  'Hugo',
  'Ignition (Bleifuss Fun)',
  'Indiana Jones and the Fate of Atlantis',
  'Jetpack',
  'Jill of the Jungle',
  'Major Stryker',
  'Maniac Mansion',
  'Math Blaster Plus!',
  'MDK',
  'Metal Slug',
  'Microsoft Flight Simulator for Windows 95',
  'Monster Truck Madness',
  'Off to Europe',
  'Operation Flashpoint: Cold War Crisis',
  'Physikus',
  'Pipe Dream',
  'Prince of Persia',
  'Professor Brösl',
  'Red Baron',
  'Shooting Gallery',
  'SimCity',
  'Space Cadet',
  'SSX Tricky',
  'Starfire',
  'Star Trek: 25th Anniversary',
  'Star Wars Episode 1: Racer',
  'Star Wars Episode 1: The Phantom Menace',
  'Star Wars Jedi Knight II: Jedi Outcast',
  'Star Wars: Rebel Assault',
  'Star Wars: Rebellion',
  'Star Wars: Rebel Assault II',
  'Star Wars: Rogue Squadron',
  'Star Wars: Shadows of the Empire',
  'Star Wars: X-Wing',
  'Star Wars: X-Wing vs TIE Fighter',
  'Star Wars: Yoda Stories',
  'Submarine Titans',
  'Sudden Strike',
  'Super Mario Bros',
  'Super Mario Land 3: Wario Land',
  'Terminal Velocity',
  'The Games: Winter Challenge',
  'The Incredible Machine',
  'The Lion King',
  'The Settlers',
  'Tintin in Tibet',
  'Tristan',
  'TZ-Minigolf',
  'Vinyl Goddess from Mars',
  'Wolfenstein 3D',
  'Wolfpack',
  'Worms',
  'Zak McKracken and the Alien Mindbenders'
];