const genres = {
  ACTION: { NAME: "Action", ID: 0 },
  ADVENTURE: { NAME: "Point & Click Adventure", ID: 1 },
  FPS: { NAME: "First-Person Shooter", ID: 2 },
  PINBALL: { NAME: "Pinball", ID: 3 },
  PLATFORMER: { NAME: "Platformer", ID: 4 },
  PUZZLE: { NAME: "Puzzle", ID: 5 },
  RACING: { NAME: "Racing", ID: 6 },
  RPG: { NAME: "Role-Playing Game", ID: 7 },
  SCROLLING_SHOOTER: { NAME: "Scrolling Shooter", ID: 8 },
  SIMULATION: { NAME: "Simulation", ID: 9 },
  SPORTS: { NAME: "Sports", ID: 10 },
  STRATEGY: { NAME: "Strategy", ID: 11 },
  TPS: { NAME: "Third-Person Shooter", ID: 12 }
}

const games = [
  { title: "3D Ultra Minigolf", genre: genres.SPORTS },
  { title: "3D Ultra Pinball", genre: genres.PINBALL },
  { title: "Action Soccer", genre: genres.SPORTS },
  { title: "Actua Soccer", genre: genres.SPORTS },
  { title: "Aladdin", genre: genres.PLATFORMER },
  { title: "Anno 1602", genre: genres.STRATEGY },
  { title: "Arcade America", genre: genres.PLATFORMER },
  { title: "Battle Chess", genre: genres.PUZZLE },
  { title: "Bernie", genre: genres.PUZZLE },
  { title: "Charlie the Clown", genre: genres.PLATFORMER },
  { title: "Comix Zone", genre: genres.PLATFORMER },
  { title: "Commander Keen in Goodbye Galaxy", genre: genres.PLATFORMER },
  { title: "Commander Keen in Keen Dreams", genre: genres.PLATFORMER },
  { title: "Conflict: Desert Storm", genre: genres.TPS },
  { title: "Crazy Gravity", genre: genres.ACTION },
  { title: "Critical Mass", genre: genres.STRATEGY },
  { title: "Day of the Tentacle", genre: genres.ADVENTURE },
  { title: "Death Rally", genre: genres.RACING },
  { title: "Eight Ball Deluxe", genre: genres.PINBALL },
  { title: "Epic Pinball", genre: genres.PINBALL },
  { title: "Fire Fight", genre: genres.ACTION },
  { title: "Galactix", genre: genres.SCROLLING_SHOOTER },
  { title: "GateWorld", genre: genres.PLATFORMER },
  { title: "Glider 4.0", genre: genres.ACTION },
  { title: "Hugo", genre: genres.ACTION },
  { title: "Ignition", genre: genres.RACING },
  { title: "Indiana Jones and the Fate of Atlantis", genre: genres.ADVENTURE },
  { title: "Jetpack", genre: genres.PLATFORMER },
  { title: "Jill of the Jungle", genre: genres.PLATFORMER },
  { title: "Major Stryker", genre: genres.SCROLLING_SHOOTER },
  { title: "Maniac Mansion", genre: genres.ADVENTURE },
  { title: "Math Blaster Plus!", genre: genres.PUZZLE },
  { title: "MDK", genre: genres.TPS },
  { title: "Metal Slug", genre: genres.PLATFORMER },
  { title: "Microsoft Flight Simulator for Windows 95", genre: genres.SIMULATION },
  { title: "Monster Truck Madness", genre: genres.RACING },
  { title: "Off to Europe", genre: genres.ACTION },
  { title: "Operation Flashpoint: Cold War Crisis", genre: genres.FPS },
  { title: "Physikus", genre: genres.PUZZLE },
  { title: "Pipe Dream", genre: genres.PUZZLE },
  { title: "Prince of Persia", genre: genres.PLATFORMER },
  { title: "Professor Brösl", genre: genres.ADVENTURE },
  { title: "Red Baron", genre: genres.SIMULATION },
  { title: "Shooting Gallery", genre: genres.ACTION },
  { title: "SimCity", genre: genres.STRATEGY },
  { title: "Space Cadet", genre: genres.PINBALL },
  { title: "SSX Tricky", genre: genres.RACING },
  { title: "Starfire", genre: genres.SCROLLING_SHOOTER },
  { title: "Star Trek: 25th Anniversary", genre: genres.SIMULATION },
  { title: "Star Wars Episode 1: Racer", genre: genres.RACING },
  { title: "Star Wars Episode 1: The Phantom Menace", genre: genres.TPS },
  { title: "Star Wars Jedi Knight II: Jedi Outcast", genre: genres.TPS },
  { title: "Star Wars: Rebel Assault", genre: genres.ACTION },
  { title: "Star Wars: Rebel Assault II", genre: genres.ACTION },
  { title: "Star Wars: Rebellion", genre: genres.STRATEGY },
  { title: "Star Wars: Rogue Squadron", genre: genres.SIMULATION },
  { title: "Star Wars: Shadows of the Empire", genre: genres.TPS },
  { title: "Star Wars: X-Wing", genre: genres.SIMULATION },
  { title: "Star Wars: X-Wing vs TIE Fighter", genre: genres.SIMULATION },
  { title: "Star Wars: Yoda Stories", genre: genres.RPG },
  { title: "Submarine Titans", genre: genres.STRATEGY },
  { title: "Sudden Strike", genre: genres.STRATEGY },
  { title: "Super Mario Bros", genre: genres.PLATFORMER },
  { title: "Super Mario Land 3: Wario Land", genre: genres.PLATFORMER },
  { title: "Terminal Velocity", genre: genres.SIMULATION },
  { title: "The Games: Winter Challenge", genre: genres.SPORTS },
  { title: "The Incredible Machine", genre: genres.PUZZLE },
  { title: "The Lion King", genre: genres.PLATFORMER },
  { title: "The Settlers", genre: genres.STRATEGY },
  { title: "Tintin in Tibet", genre: genres.PLATFORMER },
  { title: "Tristan", genre: genres.PINBALL },
  { title: "TZ-Minigolf", genre: genres.SPORTS },
  { title: "Vinyl Goddess from Mars", genre: genres.PLATFORMER },
  { title: "Wolfenstein 3D", genre: genres.FPS },
  { title: "Wolfpack", genre: genres.SIMULATION },
  { title: "Worms", genre: genres.STRATEGY },
  { title: "Zak McKracken and the Alien Mindbenders", genre: genres.ADVENTURE }
];